// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NatureAPI.Data;

#nullable disable

namespace NatureAPI.Migrations
{
    [DbContext(typeof(NatureDbContext))]
    [Migration("20251017194351_MorePhotos")]
    partial class MorePhotos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NatureAPI.Models.Entities.Amenity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Amenities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Baños"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Estacionamiento"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mirador"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Área de picnic"
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Photos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlaceId = 1,
                            Url = "https://www.mexicodesconocido.com.mx/wp-content/uploads/2016/12/nevado-de-toluca-parque-1600.jpg"
                        },
                        new
                        {
                            Id = 2,
                            PlaceId = 1,
                            Url = "https://cdn.visitmexico.com/sites/default/files/styles/explore_hero_desktop/public/2020-03/Nevado-Toluca.jpg"
                        },
                        new
                        {
                            Id = 3,
                            PlaceId = 1,
                            Url = "https://escapadas.mexicodesconocido.com.mx/wp-content/uploads/2020/10/nevado-de-toluca-foto-fernando-acosta.jpg"
                        },
                        new
                        {
                            Id = 4,
                            PlaceId = 1,
                            Url = "https://volcanesdemexico.org/wp-content/uploads/2018/12/clima-nevado-de-toluca.jpg"
                        },
                        new
                        {
                            Id = 5,
                            PlaceId = 2,
                            Url = "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/6VJHMRXIY5HKDGJ775PGPVH65Q.jpg"
                        },
                        new
                        {
                            Id = 6,
                            PlaceId = 2,
                            Url = "https://www.mexicodesconocido.com.mx/wp-content/uploads/2017/09/Cascadas-de-Tamul-San-Luis-Potosi_1200.jpg"
                        },
                        new
                        {
                            Id = 7,
                            PlaceId = 2,
                            Url = "https://www.mexicodesconocido.com.mx/wp-content/uploads/2017/01/Cascada-de-Tamasopo-San-Luis-Potosi_1920p.jpg"
                        },
                        new
                        {
                            Id = 8,
                            PlaceId = 2,
                            Url = "https://www.civitatis.com/f/mexico/san-luis-potosi/excursion-cascada-tamul-cueva-agua-589x392.jpg"
                        },
                        new
                        {
                            Id = 9,
                            PlaceId = 3,
                            Url = "https://www.caminoreal.com/storage/app/media/Blog/la-bufadora-baja-california.jpg"
                        },
                        new
                        {
                            Id = 10,
                            PlaceId = 3,
                            Url = "https://pacifica-ensenada.com/wp-content/uploads/2024/09/1000_F_347652456_i1yUhivVTHJowe9ItdXRBQntdPbc6jNe.jpg"
                        },
                        new
                        {
                            Id = 11,
                            PlaceId = 3,
                            Url = "https://www.debate.com.mx/__export/1727036211378/sites/debate/img/2024/09/22/la_bufadora.jpg_466078407.jpg"
                        },
                        new
                        {
                            Id = 12,
                            PlaceId = 3,
                            Url = "https://mediaim.expedia.com/destination/2/9a586ef50a9488138b6a62269172663b.jpg"
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Place", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accessible")
                        .HasColumnType("bit");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ElevationMeters")
                        .HasColumnType("int");

                    b.Property<double>("EntryFee")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Places");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accessible = true,
                            Category = "Parque",
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Zona volcánica con lagunas en el cráter.",
                            ElevationMeters = 4000,
                            EntryFee = 54.0,
                            Latitude = 19.1083,
                            Longitude = -99.758899999999997,
                            Name = "Parque Nacional Nevado de Toluca",
                            OpeningHours = "08:00-17:00"
                        },
                        new
                        {
                            Id = 2,
                            Accessible = true,
                            Category = "Cascada",
                            CreatedAt = new DateTime(2024, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Imponente caída de agua en la Huasteca Potosina.",
                            ElevationMeters = 300,
                            EntryFee = 40.0,
                            Latitude = 21.6937,
                            Longitude = -99.182699999999997,
                            Name = "Cascada de Tamul",
                            OpeningHours = "08:00-18:00"
                        },
                        new
                        {
                            Id = 3,
                            Accessible = true,
                            Category = "Mirador",
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Geyser marino/rezonador en la costa de Ensenada.",
                            ElevationMeters = 20,
                            EntryFee = 0.0,
                            Latitude = 31.745699999999999,
                            Longitude = -116.71469999999999,
                            Name = "La Bufadora",
                            OpeningHours = "Abierto"
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.PlaceAmenity", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("AmenityId")
                        .HasColumnType("int");

                    b.HasKey("PlaceId", "AmenityId");

                    b.HasIndex("AmenityId");

                    b.ToTable("PlaceAmenities");

                    b.HasData(
                        new
                        {
                            PlaceId = 1,
                            AmenityId = 1
                        },
                        new
                        {
                            PlaceId = 1,
                            AmenityId = 2
                        },
                        new
                        {
                            PlaceId = 1,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 2,
                            AmenityId = 1
                        },
                        new
                        {
                            PlaceId = 2,
                            AmenityId = 3
                        },
                        new
                        {
                            PlaceId = 3,
                            AmenityId = 2
                        },
                        new
                        {
                            PlaceId = 3,
                            AmenityId = 3
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Trail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double>("DistanceKm")
                        .HasColumnType("float");

                    b.Property<int>("EstimatedTimeMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsLoop")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaceId");

                    b.ToTable("Trails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Difficulty = "Alta",
                            DistanceKm = 12.0,
                            EstimatedTimeMinutes = 300,
                            IsLoop = false,
                            Name = "Sendero al Cráter",
                            Path = "[ [19.12,-99.76],[19.11,-99.75] ]",
                            PlaceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Difficulty = "Media",
                            DistanceKm = 4.5,
                            EstimatedTimeMinutes = 120,
                            IsLoop = false,
                            Name = "Mirador de Tamul",
                            Path = "[ [21.69,-99.19],[21.69,-99.18] ]",
                            PlaceId = 2
                        },
                        new
                        {
                            Id = 3,
                            Difficulty = "Baja",
                            DistanceKm = 1.2,
                            EstimatedTimeMinutes = 45,
                            IsLoop = true,
                            Name = "Costero La Bufadora",
                            Path = "[ [31.74,-116.71],[31.75,-116.71] ]",
                            PlaceId = 3
                        });
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Photo", b =>
                {
                    b.HasOne("NatureAPI.Models.Entities.Place", "Place")
                        .WithMany("Photos")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.PlaceAmenity", b =>
                {
                    b.HasOne("NatureAPI.Models.Entities.Amenity", "Amenity")
                        .WithMany("PlaceAmenities")
                        .HasForeignKey("AmenityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NatureAPI.Models.Entities.Place", "Place")
                        .WithMany("PlaceAmenities")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Review", b =>
                {
                    b.HasOne("NatureAPI.Models.Entities.Place", "Place")
                        .WithMany("Reviews")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Trail", b =>
                {
                    b.HasOne("NatureAPI.Models.Entities.Place", "Place")
                        .WithMany("Trails")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Place");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Amenity", b =>
                {
                    b.Navigation("PlaceAmenities");
                });

            modelBuilder.Entity("NatureAPI.Models.Entities.Place", b =>
                {
                    b.Navigation("Photos");

                    b.Navigation("PlaceAmenities");

                    b.Navigation("Reviews");

                    b.Navigation("Trails");
                });
#pragma warning restore 612, 618
        }
    }
}
